#!/usr/bin/env bash
# Function to display subdomain information
display_subdomain_info() {
    local domain=$1
    local subdomain=$2

    # Extract information using awk
    local info=$(awk -v sub="$subdomain" '$1 == sub {print $0}' "$domain.zone")

    if [ -n "$info" ]; then
        echo "The subdomain $subdomain is a $(echo $info | awk '{print $2}') record and points to $(echo $info | awk '{print $4}')"
    else
        echo "Subdomain $subdomain not found."
    fi
}

# Check if both domain and subdomain parameters are provided
if [ "$#" -eq 2 ]; then
    display_subdomain_info "$1" "$2"
else
    # If only domain parameter is provided, display information for default subdomains
    display_subdomain_info "$1" www
    display_subdomain_info "$1" lb-01
    display_subdomain_info "$1" web-01
    display_subdomain_info "$1" web-02
fi
