#!/usr/bin/env bash
# Configure a new ubuntu machine by installing
# Where Ngnix should be listened on porto 80
# Page where the Hello World string will be contained

apt-get update
service nginx start

echo "server {
    listen 80;
    server_name _;
    root /var/www/html;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

nginx -s reload
