#!/usr/bin/env bash
# Configure a new ubuntu machine by installing
# Where Ngnix should be listened on porto 80
# Page where the Hello World string will be contained
#

echo -e "Updating package list"

sudo apt-get update -y -qq
 echo -e "installing Nginx.\n"

sudo apt-get install  Nginx -y

sudo service nginx start

sudo ufw allow 'Ngnix HTTP'

sudo chown -R "SUSER":"SUSER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World! | dd status:none ofs/var/www/html/index.nginx-debian.html

sudo service nginx restart

echo -e "\nCompleted. \n"
