#!/usr/bin/env bash
# Configure an nginx to run and listen to Porto 80
 rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites- available/default /etc/nginx/sites-enabled/default

service nginx restart
